#the compiler
CC = g++
 
#flags:
CFLAGS  = -g -Wall

#sources of input
SOURCES = main.cpp  computing.cpp control.cpp getresults.cpp input.cpp

#sources of output
EXECUTABLE = labcalc

all:
	$(CC) $(SOURCES) $(CFLAGS) -MD -o $(EXECUTABLE) -lm